MONTHS = [
    "(1) Jan",
    "(2) Feb",
    "(3) Mar",
    "(4) Apr",
    "(5) May",
    "(6) Jun",
    "(7) Jul",
    "(8) Aug",
    "(9) Sep",
    "(10) Oct",
    "(11) Nov",
    "(12) Dec",
]

FILE_FOLDERS = {
    "Folders & Archives": [
        "zip",
        "z",
        "gz",
        "tz",
        "7z",
        "lzx",
        "rar",
        "pkg",
        "deb",
        "rpm",
    ],
    "Executables": [
        "exe",
        "app",
        "bat",
        "sh",
        "app",
        "run",
        "apk",
        "bin",
        "com",
        "wsf",
    ],
    "Text, Documents & Data": [
        "txt",
        "text",
        "doc",
        "docx",
        "rtf",
        "tex",
        "md",
        "tar",
        "json",
        "csv",
        "xml",
        "dat",
        "sql",
        "py",
        "pyc",
        "ipynb",
        "html",
        "xhtml",
        "css",
        "scss",
        "js",
        "c",
        "cpp",
        "h",
        "java",
        "jar",
        "pps",
        "ppt",
        "pptx",
        "xls",
        "xlsm",
        "xlsx",
    ],
    "Media": [
        "iso",
        "dmg",
        "vcd",
        "ttf",
        "fnt",
        "fon",
        "otf",
        "ai",
        "bmp",
        "gif",
        "jpeg",
        "jpg",
        "png",
        "psd",
        "svg",
        "pdf",
        "ico",
        "mp3",
        "mp4",
        "m4v",
        "mkv",
        "wav",
        "avi",
        "flv",
        "mpg",
        "mpeg",
        "wmv",
        "mov",
    ],
}
