MONTHS = {
    "Jan": "(1)",
    "Feb": "(2)",
    "Mar": "(3)",
    "Apr": "(4)",
    "May": "(5)",
    "Jun": "(6)",
    "Jul": "(7)",
    "Aug": "(8)",
    "Sep": "(9)",
    "Oct": "(10)",
    "Nov": "(11)",
    "Dec": "(12)",
}


FILE_FOLDERS = {
    "Folders & Archives": [
        "zip",
        "z",
        "gz",
        "tz",
        "7z",
        "lzx",
        "rar",
        "pkg",
        "deb",
        "rpm",
    ],
    "Executables": [
        "exe",
        "app",
        "bat",
        "sh",
        "app",
        "run",
        "apk",
        "bin",
        "com",
        "wsf",
    ],
    "Text, Documents & Data": [
        "txt",
        "text",
        "ini",
        "doc",
        "docx",
        "rtf",
        "tex",
        "md",
        "tar",
        "json",
        "csv",
        "xml",
        "dat",
        "sql",
        "py",
        "pyc",
        "ipynb",
        "html",
        "xhtml",
        "css",
        "scss",
        "js",
        "c",
        "cpp",
        "h",
        "java",
        "jar",
        "pps",
        "ppt",
        "pptx",
        "xls",
        "xlsm",
        "xlsx",
    ],
    "Media": [
        "iso",
        "dmg",
        "vcd",
        "ttf",
        "fnt",
        "fon",
        "otf",
        "ai",
        "bmp",
        "gif",
        "jpeg",
        "jpg",
        "png",
        "psd",
        "svg",
        "pdf",
        "ico",
        "mp3",
        "mp4",
        "m4v",
        "mkv",
        "wav",
        "avi",
        "flv",
        "mpg",
        "mpeg",
        "wmv",
        "mov",
    ],
}
