import logging
import os
import shutil
import unittest
from datetime import datetime

# Note that to run this test, you must execute:
# `python3 -m tests.main_test`
# from the main directory (where main.py is)
import main
from assets.constants import FILE_FOLDERS, MONTHS
from assets.sorter import Sorter
from tests.constants_for_tests import SAMPLE_FILES, TEST_FILE_FOLDERS, TESTS_DIR

# CONSTANTS
SAMPLE_PATH_1 = os.path.join(TESTS_DIR, "Sample Files")
SAMPLE_PATH_2 = os.path.join(TESTS_DIR, "Sample Files (2)")

TEST_COMMANDS = os.path.join(TESTS_DIR, "test_folders_to_track.txt")


## Unit tests ##
class TestMain(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(TEST_COMMANDS, "w") as new_commands:
            new_commands.write(f"{SAMPLE_PATH_1} file_type\n{SAMPLE_PATH_2} date 2018")

        # Changes where the sample_program object will read commands from
        main.COMMANDS_PATH = TEST_COMMANDS

    @classmethod
    def tearDownClass(cls):
        os.remove(TEST_COMMANDS)

        # Final assert at the end of all tests to make sure both
        # Sample Files folders are back to their original layout
        assert os.listdir(SAMPLE_PATH_1) == SAMPLE_FILES
        assert os.listdir(SAMPLE_PATH_2) == SAMPLE_FILES

    def setUp(self):
        self.sample_program = main.Main()
        self.sample_sorter = Sorter(SAMPLE_PATH_1, "date", 2018)

        self.temp_dir = None
        self.temp_month_dir = None
        self.temp_year_dir = None
        self.temp_path = None
        self.temp_month_path = None
        self.temp_year_path = None

        # Stops test from running if either folder layout is incorrect
        assert os.listdir(SAMPLE_PATH_1) == SAMPLE_FILES
        assert os.listdir(SAMPLE_PATH_2) == SAMPLE_FILES

    def tearDown(self):
        del self.sample_program
        del self.sample_sorter

    # HELPER FUNCTIONS

    def undo_date_sort(self):
        """Undoes folders generated by sort_date function from a Sorter object
        and moves files to their original folder.

        Copied but slightly modified from sorter_test.py.
        """
        for year in self.sample_sorter.years:
            self.temp_year_path = os.path.join(self.sample_sorter.folder, year)
            self.temp_year_dir = os.listdir(self.temp_year_path)

            for month in self.temp_year_dir:
                self.temp_month_path = os.path.join(self.temp_year_path, month)
                self.temp_month_dir = os.listdir(self.temp_month_path)

                # All sample files created in November 2020
                if year == "2020" and month == "(11) Nov":
                    self.temp_dir = self.temp_month_dir

                for item in self.temp_month_dir:
                    shutil.move(
                        os.path.join(self.temp_month_path, item),
                        os.path.join(self.sample_sorter.folder, item),
                    )
                os.rmdir(self.temp_month_path)
            os.rmdir(self.temp_year_path)

    # TESTS

    def test_event_handler(self):
        pass

    def test_init(self):
        pass

    def test_make_observer(self):
        pass

    def test_add_observer(self):
        pass

    def test_setup_observers(self):
        pass

    def test_run(self):
        pass


if __name__ == "__main__":
    unittest.main()
