import logging
import os
import shutil
import unittest
from datetime import datetime

# Note that to run this test, you must execute:
# `python3 -m tests.sorter_test`
# from the main directory (where main.py is)
from assets import constants
from assets.sorter import Sorter, file_handler
from tests.constants_for_tests import TEST_FILE_FOLDERS, SAMPLE_FILES, TESTS_DIR

# LOG
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

logger.addHandler(file_handler)

# SAMPLE FILES PATH
SAMPLE_PATH = os.path.join(TESTS_DIR, "SampleFiles")


## Unit Tests ##
class TestSorter(unittest.TestCase):
    @classmethod
    def tearDownClass(cls):
        # Final assert at the end of all tests to make sure the
        # Sample Files folder is back to its original layout
        assert os.listdir(SAMPLE_PATH) == SAMPLE_FILES

        logger.info("The layout of Sample Files folder is correct at the end of tests.")

    def setUp(self):
        # Sorter class instances
        # One for date and one for file type
        self.sorter1 = Sorter(SAMPLE_PATH, "date", 2018)
        self.sorter2 = Sorter(SAMPLE_PATH, "file_type")

        # Variables used in test functions
        self.temp_dirs = {}
        self.temp_dir = None
        self.temp_month_dir = None
        self.temp_year_dir = None
        self.temp_path = None
        self.temp_month_path = None
        self.temp_year_path = None
        self.temp_years = None
        self.sorter_temp = None

        # Stops test from running if folder layout is incorrect
        assert os.listdir(SAMPLE_PATH) == SAMPLE_FILES

        logger.debug("The layout of Sample Files folder is correct, test may proceed.")

    def tearDown(self):
        del self.sorter1
        del self.sorter2

    # HELPER FUNCTIONS

    def undo_file_sort(self):
        """Undoes folders generated by sort_file function and moves files to
        their original folder.

        Only for use with test_sort_file and test_sort.
        """
        for file_type in TEST_FILE_FOLDERS:
            self.temp_path = os.path.join(self.sorter2.folder, file_type)
            self.temp_dir = os.listdir(self.temp_path)
            self.temp_dirs[file_type] = self.temp_dir

            for item in self.temp_dir:
                shutil.move(
                    os.path.join(self.temp_path, item),
                    os.path.join(self.sorter2.folder, item),
                )
            os.rmdir(self.temp_path)

        logger.debug(f"After running undo_file_sort, self.temp_dirs = {self.temp_dirs}")

    def undo_date_sort(self):
        """Undoes folders generated by sort_date function and moves files to
        their original folder.

        Only for use with test_sort_date and test_sort.
        """
        for year in self.sorter1.years:
            self.temp_year_path = os.path.join(self.sorter1.folder, year)
            self.temp_year_dir = os.listdir(self.temp_year_path)

            for month in self.temp_year_dir:
                self.temp_month_path = os.path.join(self.temp_year_path, month)
                self.temp_month_dir = os.listdir(self.temp_month_path)

                # All sample files created in November 2020
                if year == "2020" and month == "(11) Nov":
                    self.temp_dir = self.temp_month_dir

                for item in self.temp_month_dir:
                    shutil.move(
                        os.path.join(self.temp_month_path, item),
                        os.path.join(self.sorter1.folder, item),
                    )
                os.rmdir(self.temp_month_path)
            os.rmdir(self.temp_year_path)

        logger.debug(f"After running undo_date_sort, self.temp_dir = {self.temp_dir}")

    # TESTS

    def test_init(self):
        self.assertEqual(self.sorter1.folder, SAMPLE_PATH)
        self.assertEqual(self.sorter2.sort_type, "file_type")
        self.assertEqual(self.sorter1.earliest_year, 2018)
        self.assertEqual(self.sorter2.earliest_year, datetime.today().year)

    def test_assert_valid(self):
        self.assertTrue(self.sorter1.assert_valid())
        self.assertTrue(self.sorter2.assert_valid())

        # Sort type
        self.sorter_temp = Sorter(SAMPLE_PATH, "string", 2018)
        self.assertFalse(self.sorter_temp.assert_valid())

        # Earliest year
        self.sorter_temp.sort_type = "date"
        self.sorter_temp.earliest_year = 1900
        self.assertFalse(self.sorter_temp.assert_valid())
        self.sorter_temp.earliest_year = 2040
        self.assertFalse(self.sorter_temp.assert_valid())
        self.sorter_temp.earliest_year = "2018"
        self.assertFalse(self.sorter_temp.assert_valid())

        # Folder
        self.sorter_temp = Sorter("./", "date")
        self.assertFalse(self.sorter_temp.assert_valid())
        self.sorter_temp.folder = "folder"
        self.assertFalse(self.sorter_temp.assert_valid())

    def test_update_dir_files(self):
        self.sorter1.update_dir_files()
        self.dir1 = self.sorter1.dir_files
        self.sorter2.update_dir_files()
        self.dir2 = self.sorter2.dir_files
        self.assertTrue(self.dir1 == self.dir2)

        self.sorter1.folder = os.path.dirname(self.sorter1.folder)
        self.sorter2.folder = os.path.dirname(self.sorter2.folder)
        self.sorter1.update_dir_files()
        self.sorter2.update_dir_files()
        self.assertNotEqual(self.dir1, self.sorter1.dir_files)
        self.assertEqual(self.sorter1.dir_files, self.sorter2.dir_files)

    def test_update_years(self):
        self.sorter1.update_years()
        self.assertTrue(self.sorter1.years)
        self.assertEqual(type(self.sorter1.years), list)
        self.assertEqual(
            self.sorter1.years,
            list(map(str, list(range(2018, datetime.today().year + 1)))),
        )

        self.sorter2.update_years()
        self.assertEqual(len(self.sorter2.years), 1)
        self.assertEqual(type(self.sorter2.years[0]), str)
        self.assertEqual(self.sorter2.years[0], str(datetime.today().year))

    def test_ensure_file_folders(self):
        self.sorter2.ensure_file_folders()
        self.sorter2.update_dir_files()

        for folder in constants.FILE_FOLDERS:
            self.assertIn(folder, self.sorter2.dir_files)
            os.rmdir(os.path.join(self.sorter2.folder, folder))

    def test_ensure_date_folders(self):
        self.sorter1.earliest_year = 2001
        self.assertTrue(self.sorter1.assert_valid())
        self.sorter1.ensure_date_folders()
        self.sorter1.update_dir_files()

        self.temp_years = list(map(str, list(range(2001, datetime.today().year + 1))))

        logger.debug(f"Variable self.temp_years = {self.temp_years}")

        for year in self.temp_years:
            self.assertIn(year, self.sorter1.dir_files)
            self.temp_path = os.path.join(self.sorter1.folder, year)
            self.temp_dir = os.listdir(self.temp_path)
            for month in constants.MONTHS:
                self.assertIn(f"{constants.MONTHS[month]} {month}", self.temp_dir)

            shutil.rmtree(self.temp_path)

    def test_sort_file(self):
        self.sorter2.ensure_file_folders()
        self.sorter2.sort_file()

        # Create duplicate file and sort again
        self.temp_path = os.path.join(self.sorter2.folder, "Executables")
        self.temp_dir = os.listdir(self.temp_path)

        shutil.copy(
            os.path.join(self.temp_path, self.temp_dir[1]),
            os.path.join(self.sorter2.folder, self.temp_dir[1]),
        )
        self.sorter2.sort_file()

        self.undo_file_sort()
        for file_type in self.temp_dirs:

            logger.debug(
                f"Checking file type: {file_type}"
                f"\nSorted folder: {self.temp_dirs[file_type]}"
                f"\nShould be: {TEST_FILE_FOLDERS[file_type]}"
            )

            self.assertEqual(self.temp_dirs[file_type], TEST_FILE_FOLDERS[file_type])

    def test_sort_date(self):
        self.sorter1.ensure_date_folders()
        self.sorter1.sort_date()

        self.undo_date_sort()

        logger.debug(
            f"Checking date sort\nSorted folder: {self.temp_dir}"
            f"\nShould be: {SAMPLE_FILES}"
        )

        self.assertEqual(self.temp_dir, SAMPLE_FILES)

    def test_sort(self):
        # DATE
        self.sorter1.sort()

        self.undo_date_sort()

        logger.debug(
            f"Checking date sort\nSorted folder: {self.temp_dir}"
            f"\nShould be: {SAMPLE_FILES}"
        )

        self.assertEqual(self.temp_dir, SAMPLE_FILES)

        # FILE TYPE
        self.sorter2.sort()

        self.undo_file_sort()
        for file_type in self.temp_dirs:

            logger.debug(
                f"Checking file type: {file_type}"
                f"\nSorted folder: {self.temp_dirs[file_type]}"
                f"\nShould be: {TEST_FILE_FOLDERS[file_type]}"
            )

            self.assertEqual(self.temp_dirs[file_type], TEST_FILE_FOLDERS[file_type])


if __name__ == "__main__":
    unittest.main()
